### ISSUE TITLE
Plakatbilder hochladbar machen

### ISSUE THREAD

**Issue by leitmedium** [bauersman/spruchomat#3]
Ich möchte Plakat-Fotos hochladen können.

**Comment by bauersman** [comment]
Ist eingebaut, passenger beschwert sich allerdings beim Hochladen von Bildern:

2013/09/13 12:03:23 [crit] 10762#0: *49 open() "/tmp/passenger-standalone.1nn7rb9/client_body_temp/0000000003" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "POST /admin/posters/1 HTTP/1.1", host: "localhost:17321", referrer: "http://plakate.volans.uberspace.de/admin/posters/1/edit"

Scheint ein Problem mit dem temporären Verzeichnis zu sein:
https://code.google.com/p/phusion-passenger/issues/detail?id=654
http://stackoverflow.com/questions/13028715/500-internal-server-error-in-ruby-on-rails

Interessanterweise bringt ein Neustart von Passenger nichts, in /tmp sind nur temporäre Verzeichnisse von anderen Passenger-Instanzen.

**Comment by leitmedium** [comment]
fixed.
